// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bisulnbxhulbddcrhfty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpc3VsbmJ4aHVsYmRkY3JoZnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTIxNjYsImV4cCI6MjA1NTQ2ODE2Nn0.ivxTdjn2Ovqd2gfW7S9rhUcrxfH_TQBYZC8Zs6o7a14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);